#DValues for staging environment
NAMESPACE: it1
FDK_MONGODB_VOLUMENAME_DB: pubapi-dev-it1-mongodb-db
FDK_MONGODB_STORAGESIZE_DB: 7G
FDK_MONGODB_VOLUMENAME_BKP: pubapi-dev-it1-mongodb-bkp
FDK_MONGODB_STORAGESIZE_BKP: 7G