name: Deploy to staging (digdir) when pull request is created

on:
  pull_request:
    branches:
      - master

jobs:
  deploy-staging:
    name: Deploy mongodb to staging environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk-mongodb https://informasjonsforvaltning.github.io/fdk-mongodb-config/
            helm fetch --untar --untardir ./helm fdk-mongodb/mongodb
            helm template -f ./helm/mongodb/values/staging-digdir.yaml ./helm/mongodb/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
          project_id: digdir-fdk-dev
          location_zone: europe-north1-a
          cluster_name: digdir-fdk-dev

      - name: Deploy to staging
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack of deploy
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C7NTH118T\",\"text\":\"Application: fdk-mongodb deployed to digdir-staging\"}'