name: Deploy to production on merge to master branch

on:
  push:
    branches:
      - master

jobs:
  deploy-production:
    name: Deploy mongodb to production environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk-mongodb https://informasjonsforvaltning.github.io/fdk-mongodb-config/
            helm fetch --untar --untardir ./helm fdk-mongodb/mongodb
            helm template -f ./helm/mongodb/values/production.yaml ./helm/mongodb/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_PROD_AUTODEPLOY }}
          project_id: fdk-prod
          location_zone: europe-north1-a
          cluster_name: fdk-prod

      - name: Deploy to production
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"

      - name: Notify slack of deploy
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C7NTH118T\",\"text\":\"Application: fdk-mongodb deployed to production\"}'